import uuid
from sqlalchemy import Column, String, DateTime, Table, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db.base import Base

memory_stories = Table(
    "memory_stories",
    Base.metadata,
    Column("memory_id", UUID(as_uuid=True), ForeignKey("memories.id", ondelete="CASCADE"), primary_key=True),
    Column("story_id", UUID(as_uuid=True), ForeignKey("stories.id", ondelete="CASCADE"), primary_key=True),
)

class Story(Base):
    """
    Phase K: First-class Story node.
    Represents a temporally coherent work session, generated by story_builder.py.
    """
    __tablename__ = "stories"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    title = Column(String(255), nullable=False)
    start_time = Column(DateTime(timezone=True), nullable=True)
    end_time = Column(DateTime(timezone=True), nullable=True)

    memories = relationship("Memory", secondary=memory_stories, back_populates="stories")

    def __repr__(self):
        return f"<Story id={self.id} title={self.title!r}>"
