"""Add vector extension and embedding column

Revision ID: 39018a2ee749
Revises: 2c766c3a59a7
Create Date: 2026-08-31 23:04:07.991106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '39018a2ee749'
down_revision: Union[str, Sequence[str], None] = '2c766c3a59a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.execute("CREATE INDEX IF NOT EXISTS ix_memories_embedding ON memories USING hnsw (embedding vector_cosine_ops);")
    op.alter_column('memories', 'embedding_placeholder',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Placeholder — Phase C migrates this to vector(768)',
               existing_nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memories', 'embedding_placeholder',
               existing_type=sa.TEXT(),
               comment='Placeholder — Phase C migrates this to vector(768)',
               existing_nullable=True)
    op.drop_column('memories', 'embedding')
    # ### end Alembic commands ###
